### ISSUE TITLE
Error in Step 

### ISSUE THREAD

**Issue by em0ral** [mweisel/gns3-server-orbstack#1]
ansible all -m ping

gns3@orb | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname orb: nodename nor servname provided, or not known",
    "unreachable": true
}

Please help!

**Comment by mweisel** [comment]
Refer to [SSH access](https://docs.orbstack.dev/machines/ssh) to help troubleshoot. [gns3@orb](https://github.com/mweisel/gns3-server-orbstack/blob/65048da6a26b52e7ba943c36de72cc03ecd46ab3/inventory/hosts.yml#L4) is the sole host in the Ansible [inventory](https://docs.orbstack.dev/machines/ssh#ansible).
